### ISSUE TITLE
Um?

### ISSUE THREAD

**Issue by MaxVFF** [ProtoGrace/Gmod-Backdoor-Scanner#9]
When I tried using it, it called me a "skid" and turned my computer off.
My computer is still off and I do not know what to do?
![image](https://user-images.githubusercontent.com/84413476/118717284-df867900-b7f3-11eb-8618-1136ddabbddb.png)

**Comment by wizar-d** [comment]
it got backdoored as of the newest update

**Comment by ProtoGrace** [comment]
False

**Comment by MaxVFF** [comment]
real, check screenshot
